### ISSUE TITLE
Crash when a font is missing

### ISSUE THREAD

**Issue by swiftsword7** [christopho/solarus#663] opened 2015-03-24 00:28 UTC
Solarus.exe crashes after logo.

**Comment by Renkineko** [comment] 2015-03-24 06:13
Have you a message when it crashes ? Can you paste the content of error.txt in the same directory as solarus.exe ? Just a "it crashes after logo" don't help a lot ;)

**Comment by swiftsword7** [comment] 2015-03-24 12:00
Sorry but there isn't a valid error.txt

**Comment by christopho** [comment] 2015-03-24 13:07
Solarus does not crash after the logo for me, so we need more information to reproduce the problem. Can you send your quest data?

**Comment by swiftsword7** [comment] 2015-03-24 19:50
How?

**Comment by christopho** [comment] 2015-03-24 21:38
Please contact me by email: christopho at solarus-games.org.

**Comment by swiftsword7** [comment] 2015-03-25 13:21
I did.

**Comment by christopho** [comment] 2015-03-25 13:38
Thanks, please send me your quest data by email (or a link to them) so I can reproduce the problem.

**Comment by swiftsword7** [comment] 2015-03-26 12:48
I did

**Comment by swiftsword7** [comment] 2015-03-27 12:31
Please help!

**Comment by christopho** [comment] 2015-03-27 14:24
If you are in a hurry, maybe you could publish your game data (or better, give an example of code that isolates the bug) so that anyone can help.
There are currently 68 other open issues. I work on them when I can.

**Comment by swiftsword7** [comment] 2015-03-27 16:05
I can wait, is there anything I can do to help find the bug?

**Comment by christopho** [comment] 2015-04-01 15:40
The crash was due to missing font files. Your text/fonts.dat file declares 3 fonts but the font file only exists for one of them.
This problem is already fixed in Solarus 1.4, where missing font files are indicated in the quest editor, and at runtime, an message is displayed.

Solarus 1.4 is not released yet, but in the meantime, you can either get the 2 missing font files (I think they are created when you create a new quest) or remove their declaration in text/fonts.dat.

**Closed by christopho** 2015-04-01 15:40 UTC
Labels: bug
