### ISSUE TITLE
Error: Failed to create software surface

### ISSUE THREAD

**Issue by wrightmat** [christopho/solarus#933] opened 2016-07-16 02:19 UTC
I get this error periodically without any indication of the cause. I'm assuming it's from re-drawing a surface too much, such as with a night overlay. Not sure if this is something that can be optimized in the engine (or at least a more descriptive error message).

**Comment by christopho** [comment] 2016-07-16 03:43
Is there an easy way to reproduce the problem?

**Comment by wrightmat** [comment] 2016-07-16 15:01
Using the code that Satoh posted to the forum at http://forum.solarus-games.org/index.php/topic,676.15.html. If the map is played long enough, you should get the crash. I thought it was because the surface is basically cleared and re-drawn on every draw cycle, but I don't think there's another way to do it and get the same results.

**Comment by MetalES** [comment] 2016-07-22 16:40
I got this error recently while making the minimap script, I don't know how I fixed it

**Comment by wrightmat** [comment] 2016-08-03 02:10
I can say almost certainly that this is related to the clear() function. If that is changed to fill_color() in code then I don't get the crash.

**Comment by christopho** [comment] 2016-08-03 07:01
@wrightmat Does the crash happens with and without 2D acceleration?
Do you see the memory usage grow before the crash? (i.e., I want to know if this is an out-of-memory error)

**Comment by MetalES** [comment] 2016-08-03 11:01
There is a huge performance issue before the crash happend, there will be major slowdowns that will be there for the whole game (even if you change map, it will be laggy) and then the crash happen.
Sometimes, trying to close the no longer playing game is impossible, memory is saturated.

**Comment by MetalES** [comment] 2016-08-03 11:08
@wrightmat There are no more lags when exiting an inside place, but there is still the huge lags in Interloper Sanctum and in inside places where the effect is used (is the sprite recreated each time the animation is finished ?)

**Comment by christopho** [comment] 2016-08-03 11:28
@MetalES @wrightmat Does the crash happens with and without 2D acceleration?

**Comment by MetalES** [comment] 2016-08-03 12:03
I'm gonna test without 2d acceleration and post the answer.

**Comment by wrightmat** [comment] 2016-08-03 14:54
It did not crash for me (in Interloper Sanctum) without 2D acceleration when I played for about a half hour. It does lag quite a bit without it on though.

**Comment by christopho** [comment] 2016-08-03 16:16
Ok, so there must be a memory leak related to clear() when 2D acceleration is used. This is not surprising because surface algorithms are much more complex.

**Comment by MetalES** [comment] 2016-08-03 21:28
Same as @wrightmat, nothing much without 2d acceleration.

Should I ask what 2d acceleration really do ? Is it necessary for old-specs PC ?

**Comment by MetalES** [comment] 2016-08-09 12:57
Strange anomaly is: I am playing the latest version of Book of Mudora.
I am standing still at Kakarico, night time, so the light effect is active.

The Engine RAM consumption gets bigger and bigger when the light effect is drawn
CPU never go down 25% of use

2D acceleration is disabled

When I entered the map I was around 225 000 kb (225mb)
Now I am at 600 000 (~600 mb), I didn't do anything much

Don't know if it is related to wrightmat's code or if it is related to the memory leak

**Comment by wrightmat** [comment] 2016-08-11 15:41
I did replace clear() with fill_color() and it definitely helped, but didn't fix the problem entirely. Before I could only play on a map with drawing for 10 or 15 minutes, but with clear() instead I can get 30 minutes or more (but it still crashes eventually). Turning off 2d acceleration doubled that time again, but it still crashed eventually.

**Comment by christopho** [comment] 2016-08-22 17:39
@wrightmat @MetalES can you confirm if the bug is fixed with this snapshot: http://www.solarus-games.org/downloads/solarus/win32/solarus-1.5.1-snapshot-20160822-win32.zip
Thanks

**Closed** 2016-08-23 20:55 UTC
Labels: bug
