### ISSUE TITLE
Feature request: more customization for animated tiles

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#704] opened 2015-07-02 07:19 UTC
For animated tiles, it would be nice to have more customization, namely:
-The speed of the animation, optional (we can keep the current one as default).
-The number of frames of the animation (at present, only multiples of 3 are allowed for cyclic animations).

**Comment by christopho** [comment] 2015-07-02 08:10
Duplicate of #683.

**Closed by christopho** 2015-07-02 08:10 UTC
