### ISSUE TITLE
cmake and libraries part

### ISSUE THREAD

**Issue by david-geiger** [christopho/solarus#765] opened 2015-09-03 11:55 UTC
Hi,

I see that on latest 1.4.4 release we have an new development part with include files and library file, but there is only a "libsolarus.so" file.

Is possible to create other libraries files?  i-e:

- libsolarus.so.1.4.4 must be the main library
- libsolarus.so.1 must be a symlink to libsolarus.so.1.4.4
- libsolarus.so must be a symlink to libsolarus.so.1.4.4 too.

So with this change on a rpm package we get:
- 'libsolarus.so' goes into a devel subpackage
- 'libsolarus.so.1' and 'libsolarus.so.1.4.4' go into a library subpackage

Many developer uses this method for libraries files.

BTW: the major '1' and '1.4.4' is an example you can use something else :)

Best regards David.

**Comment by Nate-Devv** [comment] 2015-09-03 21:38
I do not see the point of this. Solarus is multiplatform, so efforts are better spent improving the engine as a whole than making a change like this.  Also, there isn't much of a need to make many separate packages. The use case of only needing the library file is nonexistent or very rare at best, because this is a game engine and needs the actual executable by the nature of the project.
The equivalent of a 'devel' subpackage is in the solarus quest editor.

**Comment by david-geiger** [comment] 2015-09-08 17:30
No! I'm not agree with you on that point:

devel files should be, and only, in a 'devel' subpackage and library files should be also in a 'library' subpackage and not in the main package 'solarus'.

If I built all files in the same 'solarus' package I get these rpmlint warnings:

http://pastebin.com/TzbWA5qB

**Comment by Nate-Devv** [comment] 2015-09-08 22:54
The Library file and Include files have their own cmake files. Does that help?

**Comment by Nate-Devv** [comment] 2015-09-08 23:01
I'm working on Debian, and you're working on an rpm distro. I'm going to see about splitting the package up and I'll come back with my results.

**Comment by Nate-Devv** [comment] 2015-09-08 23:09
There are no 'devel' files, and while a 'library' package may be desired, the 'library' subpackage and the executable package would have to be interdependent on each other. It makes no contextual sense to use one without the other.

**Comment by christopho** [comment] 2015-12-04 12:20
Duplicate of #800, already fixed.

**Closed by christopho** 2015-12-04 12:20 UTC
