### ISSUE TITLE
Freezing hero should not stop the hurt built-in state

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#804] opened 2015-12-16 07:58 UTC
I have the following problem, that could be related to https://github.com/christopho/solarus/issues/764#.

I am using my own scripts to allow carrying custom entities. When the hero is hurt, the carried entity is thrown away (it just falls); I did this by overriding the function hero:on_taking_damage(damage). When I throw the entity, the hero is frozen while his throwing animation is played and then unfrozen again. The problem is that when the hero is hurt while carrying a custom entity, he is hurt twice. I suppose that the bug is caused because I freeze/unfreeze the hero while he is being hurt. 

Maybe the problem is that freezing the hero stops the hurt state, but I am not sure.

**Comment by christopho** [comment] 2015-12-16 09:29
Freezing the hero means setting the "freezed" state, so it does stops the "hurt" state.
I am not sure why the hero is hurt a second time though.

**Comment by Diarandor** [comment] 2015-12-16 16:13
I will test again soon this problem to confirm it. I think what happens is the following: when the hero is frozen/unfrozen, the built-in state changes from hurt to frozen and then to free, so he can be hurt again in that instant. The enemy I was using does not push the hero, so there is again a collision and so the hero is hurt twice.

I am starting to think that this is the expected behaviour and not a bug, since we are changing the built-in state when we freeze/unfreeze.

**Comment by christopho** [comment] 2015-12-16 19:21
Ok. hero:unfreeze() sets the state to "free" so if there is still a collision, it is indeed normal that he gets hurts again.
A way to avoid that is to use hero:set_invincible(delay) to temporarily make the hero invincible.

Closing the issue as not a bug as discussed.

**Closed by christopho** 2015-12-16 19:21 UTC

**Comment by Diarandor** [comment] 2015-12-16 21:35
I tried to use hero:set_invincible([invincible, [duration]]), but I think it does not work.
I removed the event "hero:on_taking_damage(damage)" and wrote "hero:set_invincible(true)" in some script and the hero is still receiving damage. 

I think that the function "hero:set_invincible([invincible, [duration]])" is not working. I opened a new issue for this here: https://github.com/christopho/solarus/issues/805.

**Comment by Diarandor** [comment] 2015-12-17 05:00
At the end I removed the freeze/unfreeze functions from my script, so I have no more trouble with this issue.
